### ISSUE TITLE
Clarity in your homework

### ISSUE THREAD

**Issue by jrabasco** [Merinorus/adaisawesome#2]
Hello,
I just graded your third assignment. It is not completely clear what file is supposed to be the actual final result of your work. I would greatly appreciate if you could only hand in _ONE_ IPython notebook or provide an explanation of the structure in the `README.md` of your homeworks.

**Comment by Merinorus** [comment]
Hello,

Sorry for the inconvenience... I put an explanation at the beginning of the
Readme file saying that only the HW3_Interactive_Viz.ipynb has to be
checked. But this is not clear enough, we should have removed all the other
files anyway.
Thank you for your feedback !

**Comment by jrabasco** [comment]
No worries.
